### ISSUE TITLE
Operations on incompatible types should throw a warning

### ISSUE THREAD

**Issue by roy100** [productml/blurr#135]
Chronicles from debugging land. 

The raw data had `"txn_amount": "9.99"` and the DTC had a field calculated as follows: 

```yaml
     - Name: purchase_amount
       Type: float
       Value: source.txn_amount + game_stats.purchase_amount
       When: source.event_id == 'purchase' and source.purchase_source == 'offer'
```

Since source.txn_amount is stored as text, this does not work unless the Value is written as `Value: float(source.txn_amount) + game_stats.purchase_amount`

This is of course expected behavior but it would have really helped if the transform command threw a warning saying that casting to the required type failed.
