### ISSUE TITLE
Show warning if attempting to split using a field value that doesn't exist

### ISSUE THREAD

**Issue by roy100** [productml/blurr#136]
I was trying to split by session_id `Split: source.session_id != game_stats.session_id #game_stats is the name of the DataGroup` but I had not defined a session_id field in the DataGroup. Therefore, the split condition never evaluated to True. 

Would be nice if a warning was shown if attempting to split on a field that is not defined. 

Even better would be having the ability to define a split without needing to explicitly define session_id as a field. We do this for time, why not for session_id as well?

The solution was:

```
   Split: source.session_id != game_stats.session_id

   Fields:
     - Name: session_id
       Type: string # String is the default type and is used if type is not defined
       Value: source.session_id
```
