### ISSUE TITLE
Add Syntax Validation for DTCs

### ISSUE THREAD

**Issue by mserranom** [productml/blurr#21]
Initial implementation has validation methods implemented for each element in a DTC. 

Using a YAML Schema tool such as [Yamale](https://github.com/23andMe/Yamale) we can offload syntax validation from the code, which should result in a more robust codebase.

Same as a compiler has 3 stages: lexical, syntactic and semantic analysis, this will result in schema validation splitted into 3 parts:
- Lexical Analysis ~ YAML Reader (The DTC is a correct YAML that is stored in a Dictionary)
- Syntax Analysis ~ Syntax Validation with a Schema (e.g. there's no `Type` in field with an incorrect value)
- Semantic ~ Validation in each class (e.g. `SourceDTC`) points to a correct DTC.

A schema would look like this for streaming schemas:

```yaml
Type: enum('ProductML:DTC:Streaming')
Version: enum('2018-03-01')
Description: string(min=1, required=False)
Name: identifier()
Identity: expression()
Time: expression(required=False)
Filter: expression(required=False)
Store: include('dynamodb_store')
DataGroups: list(any(include('data_group_variable'), include('data_group_identity', include('data_group_session'), min=1)

---

data_group_variable:
  Name: identifier()
  Type: enum('ProductML:DTC:DataGroup:Variable')
  Store: identifier(required=False)
  Filter: expression(required=False)
  Fields: list(include('field'), min=1)

data_group_identity:
  Name: identifier()
  Type: enum('ProductML:DTC:DataGroup:IdentityAggregate')
  Store: identifier(required=False)
  Filter: expression(required=False)
  Fields: list(include('field'), min=1)

data_group_session:
  Name: identifier()
  Type: enum('ProductML:DTC:DataGroup:SessionAggregate')
  Store: identifier(required=False)
  Filter: expression(required=False)
  Split: expression(required=False)
  Fields: list(include('field'), min=1)

field:
  Name: identifier()
  Type: data_type(required=False)
  Value: expression()
  Filter: expression(required=False)
  Atomic: bool(required=False)

dynamodb_store:
  Type: enum('ProductML:DTC:Store:DynamoDB')
  Name: identifier()
  RetentionDays: int(min=1, required=False)
  ReadWriteUnits: int(min=1, required=False)
  Table: ProductML_Test_Sessions
```
